import type { User, Recipe } from './types';

export const MOCK_USERS: User[] = [
  { id: 'user-1', name: 'Alice Johnson', email: 'alice@example.com', profilePhoto: 'https://picsum.photos/id/1011/100/100', savedRecipeIds: ['recipe-2'] },
  { id: 'user-2', name: 'Bob Smith', email: 'bob@example.com', profilePhoto: 'https://picsum.photos/id/1012/100/100', savedRecipeIds: [] },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'recipe-1',
    title: 'Classic Spaghetti Carbonara',
    description: 'A creamy and delicious Italian pasta dish made with eggs, cheese, pancetta, and pepper. A true Roman classic.',
    ingredients: ['200g Spaghetti', '100g Pancetta', '2 large Eggs', '50g Pecorino cheese', 'Black pepper'],
    steps: ['Boil spaghetti.', 'Fry pancetta until crisp.', 'Whisk eggs and cheese.', 'Combine everything off heat.'],
    category: 'Italian',
    prepTime: 20,
    imageURL: 'https://picsum.photos/id/1060/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-2',
    title: 'Spicy Chicken Tacos',
    description: 'Flavorful chicken tacos with a spicy kick, fresh salsa, and a creamy avocado sauce. Perfect for a weeknight dinner.',
    ingredients: ['2 Chicken breasts', '1 packet Taco seasoning', '8 small Tortillas', '1 cup Salsa', '1 Avocado'],
    steps: ['Cook chicken with seasoning.', 'Warm tortillas.', 'Assemble tacos with toppings.'],
    category: 'Mexican',
    prepTime: 25,
    imageURL: 'https://picsum.photos/id/24/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-7',
    title: 'Butter Chicken',
    description: 'A rich and creamy Indian curry with tender chicken pieces in a buttery tomato sauce.',
    ingredients: ['500g Chicken breast', '1 cup Tomato puree', '1/2 cup Heavy cream', '2 tbsp Butter', 'Garam masala'],
    steps: ['Marinate chicken in yogurt and spices.', 'Cook chicken in a pan.', 'Prepare the tomato gravy with butter and cream.', 'Combine chicken and gravy, and simmer.'],
    category: 'Indian',
    prepTime: 40,
    imageURL: 'https://picsum.photos/id/1068/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-3',
    title: 'Vegan Lentil Soup',
    description: 'A hearty and nutritious vegan lentil soup, packed with vegetables and flavor. Comfort food at its best.',
    ingredients: ['1 cup Brown lentils', '1 Onion', '2 Carrots', '2 Celery stalks', '4 cups Vegetable broth'],
    steps: ['Sauté vegetables.', 'Add lentils and broth.', 'Simmer for 30 minutes.'],
    category: 'Vegan',
    prepTime: 45,
    imageURL: 'https://picsum.photos/id/200/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-4',
    title: 'Blueberry Pancakes',
    description: 'Fluffy and light pancakes studded with juicy blueberries. The perfect way to start your day!',
    ingredients: ['1 cup All-purpose flour', '1 tbsp Sugar', '1 tsp Baking powder', '1/2 cup Milk', '1 Egg', '1/2 cup Blueberries'],
    steps: ['Mix dry ingredients.', 'Mix wet ingredients.', 'Combine and fold in blueberries.', 'Cook on a griddle.'],
    category: 'Breakfast',
    prepTime: 15,
    imageURL: 'https://picsum.photos/id/103/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-8',
    title: 'Palak Paneer',
    description: 'A popular vegetarian dish from North India consisting of paneer in a thick paste made from puréed spinach.',
    ingredients: ['200g Paneer', '500g Spinach', '1 Onion', '2 Tomatoes', 'Ginger-garlic paste', 'Spices'],
    steps: ['Blanch and puree spinach.', 'Sauté onions, tomatoes, and spices.', 'Add spinach puree and cook.', 'Add paneer cubes and simmer.'],
    category: 'Indian',
    prepTime: 35,
    imageURL: 'https://picsum.photos/id/372/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-5',
    title: 'Homemade Pizza',
    description: 'Classic homemade pizza with your favorite toppings. Better than takeout!',
    ingredients: ['1 Pizza dough', '1/2 cup Pizza sauce', '1 cup Mozzarella cheese', 'Pepperoni'],
    steps: ['Preheat oven to 475°F.', 'Roll out dough.', 'Add sauce, cheese, and toppings.', 'Bake for 10-12 minutes.'],
    category: 'Italian',
    prepTime: 30,
    imageURL: 'https://picsum.photos/id/312/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-6',
    title: 'Chocolate Avocado Mousse',
    description: 'A surprisingly delicious and healthy dessert. Creamy, rich, and completely dairy-free.',
    ingredients: ['2 ripe Avocados', '1/2 cup Cocoa powder', '1/2 cup Maple syrup', '1/4 cup non-dairy Milk', '1 tsp Vanilla extract'],
    steps: ['Combine all ingredients in a blender.', 'Blend until smooth.', 'Chill for at least 30 minutes.'],
    category: 'Dessert',
    prepTime: 10,
    imageURL: 'https://picsum.photos/id/431/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-9',
    title: 'California Sushi Roll',
    description: 'A classic and refreshing sushi roll with crab, avocado, and cucumber. Perfect for beginners.',
    ingredients: ['2 cups Sushi rice', '3 sheets Nori', '1/2 lb Imitation crab', '1 Avocado', '1/2 Cucumber', 'Soy sauce'],
    steps: ['Prepare sushi rice.', 'Lay nori on a bamboo mat, spread rice.', 'Add fillings and roll tightly.', 'Slice into pieces.'],
    category: 'Japanese',
    prepTime: 50,
    imageURL: 'https://picsum.photos/id/292/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-10',
    title: 'Classic Greek Salad',
    description: 'A refreshing and healthy salad with crisp lettuce, tomatoes, cucumbers, olives, and feta cheese.',
    ingredients: ['1 head Romaine lettuce', '1 cup Cherry tomatoes', '1 Cucumber', '1/2 cup Kalamata olives', '1/2 cup Feta cheese', 'Olive oil vinaigrette'],
    steps: ['Chop all vegetables.', 'Combine in a large bowl.', 'Toss with vinaigrette and top with feta.'],
    category: 'Mediterranean',
    prepTime: 15,
    imageURL: 'https://picsum.photos/id/1080/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-11',
    title: 'Beef Bourguignon',
    description: 'A savory French beef stew braised in red wine, with mushrooms, carrots, and pearl onions.',
    ingredients: ['2 lbs Beef chuck', '1 bottle Red wine (Burgundy)', '1 cup Beef broth', '8 oz Mushrooms', '2 Carrots', '1 cup Pearl onions'],
    steps: ['Sear beef until browned.', 'Sauté vegetables.', 'Deglaze pan with wine, add broth and beef.', 'Simmer for 2-3 hours until tender.'],
    category: 'French',
    prepTime: 180,
    imageURL: 'https://picsum.photos/id/658/600/400',
    author: MOCK_USERS[0],
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recipe-12',
    title: 'Chocolate Lava Cakes',
    description: 'Decadent individual chocolate cakes with a gooey, molten center. A perfect dessert for any occasion.',
    ingredients: ['4 oz Bittersweet chocolate', '1/2 cup Butter', '2 Eggs', '2 Egg yolks', '1/4 cup Sugar', '2 tbsp Flour'],
    steps: ['Melt chocolate and butter.', 'Whisk eggs, yolks, and sugar.', 'Combine mixtures, then add flour.', 'Bake in ramekins for 12-14 minutes.'],
    category: 'Dessert',
    prepTime: 25,
    imageURL: 'https://picsum.photos/id/219/600/400',
    author: MOCK_USERS[1],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const RECIPE_CATEGORIES = ['Italian', 'Mexican', 'Indian', 'Japanese', 'French', 'Mediterranean', 'Vegan', 'Breakfast', 'Dessert', 'Quick & Easy', 'Dinner'];

export const PREP_TIME_OPTIONS = [
  { label: 'Under 15 min', value: '0-15' },
  { label: '15-30 min', value: '15-30' },
  { label: '30-60 min', value: '30-60' },
  { label: 'Over 60 min', value: '60+' },
];